artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: "https://0x0.st/HYzm.zip"
  local_data_path: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion